### ISSUE TITLE
Couverture en PDF avec logo et bas de page du labo

### ISSUE THREAD

**Issue by ktzanev** [labopp/livretaccueil-sphinx#2]
Est-ce que @burnol-math pourra nous corriger vitte fait bien fait les couvertures des documentations pour qu'elle soient avec le logo du labo en haut à gauche et avec le bas de page du labo ?

**Comment by ghost** [comment]
et où trouve-t-on ce fameux logo du labo ? encore un truc qui a dû nous coûter une fortune via externalisation ;-)

**Comment by ktzanev** [comment]
Ahhh effectivement il faut les mettre sous labopp tous ces sites que je garde sous ktzanev. A suivre ...

**Comment by ktzanev** [comment]
Le liens directes sont : 
- https://ktzanev.github.io/logolabopp/logonompp/logonompp.pdf
- https://ktzanev.github.io/logolabopp/latex/labofooter.pdf

**Comment by ghost** [comment]
je m'en occuperai (peut-être demain), pas de soucis, merci pour les liens.

**Comment by ktzanev** [comment]
Super merci !
